In [ ]:
import torch

In [ ]:
device ='cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
device

'cuda'

In [ ]:
newarray=torch.tensor([[1,2,3],[2,3,4]],dtype=torch.float32,device=device,requires_grad=True)

In [ ]:
newarray

tensor([[1., 2., 3.],
        [2., 3., 4.]], device='cuda:0', requires_grad=True)

In [ ]:
newarray.dtype

torch.float32

In [ ]:
newarray.device

device(type='cuda', index=0)

In [ ]:
newarray.requires_grad

True

In [ ]:
randomarray=torch.rand((2,3))

In [ ]:
randomarray

tensor([[0.5054, 0.9650, 0.3474],
        [0.0556, 0.1294, 0.8827]])

In [ ]:
eyearray=torch.eye(3,3)

In [ ]:
eyearray

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
zeroarray=torch.zeros((2,2))

In [ ]:
zeroarray

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
onesarray=torch.ones((3,3))

In [ ]:
onesarray

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
arrangearra=torch.arange(start=0,end=11,step=2)

In [ ]:
arrangearra

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
linespance=torch.linspace(start=0.1,end=5,steps=5)

In [ ]:
linespance

tensor([0.1000, 1.3250, 2.5500, 3.7750, 5.0000])

In [ ]:
tensor=torch.arange(4)

In [ ]:
tensor


tensor([0, 1, 2, 3])

In [ ]:
x=torch.randn((3,3))
x

tensor([[ 0.7967,  3.3362, -0.4167],
        [ 0.9628,  2.1026, -0.1127],
        [ 1.5516, -1.4524, -1.3996]])

In [ ]:
y=torch.zeros((3,3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x*y

tensor([[0., 0., -0.],
        [0., 0., -0.],
        [0., -0., -0.]])